//Anna Alberti
//aca5z
//9/19/2021
//name of file: inlab4.cpp


#include <iostream>
#include <climits>
using namespace std;

int main(){
bool b = true;
char c ='a';
int i = 0;
double d = 2.0;
 unsigned int uInt = 0;
 float f0 = 0;
 float f1 = 1;
 double d0 = 0;
 double d1 = 1;
 char c0 = 0;
 char c1 = 1;
 int* intstar = NULL;
 char* charstar = NULL;
 double* doublestar = NULL;

 cout << b << endl;
 cout << c << endl;
 cout << i << endl;
 cout << d << endl;

  }
